# -*- coding: utf-8 -*-
"""diabetes_predictor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qq0Ju_qB6Qnk8b8QxlEVK07udGalDKq_
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

df_diabetes_data=pd.read_csv("pima-indians-diabetes.data")

df_diabetes_data.head()

feature_names=['Pregnant','glucose','bp','skin','insulin','bmi','pedigree','age','label']

df_diabetes_data=pd.read_csv("pima-indians-diabetes.data",names=feature_names)

df_diabetes_data.head()

feature_select_col=['Pregnant','insulin','bmi','age']
X_feature=df_diabetes_data[feature_select_col]
Y_target=df_diabetes_data['label']

X_feature.shape

Y_target.shape
Y_target.head()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X_feature,Y_target,random_state=1)

from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()
logreg.fit(x_train,y_train)

y_pred=logreg.predict(x_test)

from sklearn import metrics
print(metrics.accuracy_score(y_test,y_pred))

"""0->means no diabetes detected
1-> means diabetes  detected
"""

print("actual",y_test.values[0:30])
print("  pred",y_pred[0:30])